# Generated by Django 4.1.5 on 2023-01-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Packages',
        ),
    ]
