# Generated by Django 4.1.5 on 2023-01-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_package_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
