# Generated by Django 4.1.5 on 2023-01-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_packages_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='BookingPackage',
        ),
        migrations.RenameModel(
            old_name='Packages',
            new_name='Product',
        ),
    ]
