# Generated by Django 4.1.5 on 2023-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellerdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='travellerdetails',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='travellerdetails',
            name='email',
        ),
        migrations.AddField(
            model_name='travellerdetails',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
